"Settings

"Mappings  noremap \ ,
filetype on 
filetype plugin on 
syntax enable
let mapleader = "\<space>"
set grepprg=ag
autocmd filetype php set formatoptions+=t
runtime macros/matchit.vim
set tags=./tags,./.git/tags,../.git/tags
" this harder to deploy normal commands with this setting
" set relativenumber
"vim will treat all numerals as decimals, useful on num<C-a> with numbers like 007
set nrformats=
set splitbelow
setlocal nospell
set completeopt=menu
set backspace=indent,eol,start
set cot+=menuone
set noswapfile
set nobackup
set nowritebackup
set number
set shell=/bin/zsh
set encoding=utf-8
set scrolloff=3
set showmode
set showcmd
"use the bnext and cnext without a trailing bang
set hidden
set wildmenu
"to autocomplete the suggestions like bash
set wildmode=longest,list
"to autocomplete like zsh
"set wildmenu
"set wildmode=full
set ttyfast
set ruler
set laststatus=2
set undodir=/home/jean/.vim/undo/
set undofile
set undolevels=1000
set undoreload=10000
set hlsearch
" match while typing the search
set incsearch
set ignorecase
set smartcase
set copyindent
set autoindent
set gdefault
"indenting
filetype plugin indent on
set tabstop=4
au FileType ruby setl tabstop=2
set shiftwidth=4
au FileType ruby setl shiftwidth=2
" set softtabstop=4
set expandtab
" set shiftround
set guiheadroom=0
set antialias
"set runtimepath+=/home/jean/.vim/snippets
set mouse=a
set showmatch
set autoread
" set smarttab
"the quantity of normal commands recorded
set history=1000
set title
" set visualbell
set cursorline
" if exists("g:ctrl_user_command")
"       unlet g:ctrlp_user_command
" endif
set wildignore=*.swp,*.back,*.pyc,*.class,*.coverage.*,*\\vendor\\**
set backupdir=~/.tmp
set directory=~/.tmp "don't clutter dirs with swp and tmpfiles
set lazyredraw "don't redraw screend when running macros
highlight StatusLine ctermfg=blue ctermbg=yellow
" Display extra whitespace
set list listchars=tab:»·,trail:·

setlocal formatoptions=1
set complete+=s
set formatprg=par
setlocal linebreak
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
let g:abolish_save_file = '/home/jean/.vim/abbreviations.vim'
set clipboard=unnamedplus
"improve sytax highlight performance {{{
syntax sync minlines=256
set nocursorcolumn
set nocursorline
set norelativenumber
autocmd BufEnter * :syn sync maxlines=500
set synmaxcol=200  
"}}}
autocmd FileType markdown set commentstring=<!!--\ %s\ -->
"CTRLP with regex by default
" let g:ctrlp_regexp = 0
":nnoremap <Space> @q
"disable search continuation on edges
"set nowrapscan
"no octal
"performance tweaks
"au FileType php setl ofu=phpcomplete#CompletePHP
" au FileType html,xhtml setl ofu=htmlcomplete#CompleteTags
" au FileType c setl ofu=ccomplete#CompleteCpp
" au FileType css setl ofu=csscomplete#CompleteCSS
au FileType markdown setl tw=66
au Filetype markdown setl formatoptions+=t
au FileType TEX setl tw=66
au Filetype TEX setl formatoptions+=t
" set list listchars=tab:\ \ ,trail:•
set shortmess+=I
" autocmd BufWinEnter * highlight ColorColumn ctermbg=darkred
" highlight OverLength ctermbg=red ctermfg=white guibg=#666666
" match OverLength /\%81v.\+/
"turn the 120 chars column to red
" set colorcolumn=120

set guifont=Consolas\ 12
"set guioptions-=m  "remove menu bar
"set guioptions-=T  "remove toolbar
"set guioptions-=r  "remove right-hand scroll bar
"set guioptions-=L  "remove left-hand scroll bar
set nocompatible
hi MatchParen cterm=none ctermbg=black ctermfg=yellow
" Make it more obviouser when lines are too long
highlight ColorColumn ctermbg=235


let theme=$THEME
set background=dark
if theme == 'light'
    set background=light
else
    set background=dark
endif

set foldmethod=marker
autocmd BufRead * setlocal foldmethod=marker
autocmd BufRead * normal zM

"Plugins
call plug#begin()

"PluginsList
" Plug 'mtth/scratch.vim'
"Plug '2072/PHP-Indenting-for-VIm'
"Plug 'Shougo/neocomplcache'
"Plug 'Shougo/vimshell'
"Plug 'godlygeek/tabular'
" Interactive command execution in Vim. 
Plug 'rust-lang/rust.vim', { 'for': [ 'rust'] }
Plug 'derekwyatt/vim-scala', { 'for': [ 'scala'] }
Plug 'Shougo/vimproc'
Plug 'vimwiki/vimwiki'
Plug 'vim-scripts/Align' | Plug 'vim-scripts/SQLUtilities'
" Unite and create user interfaces
Plug 'https://github.com/Shougo/unite.vim.git'
"Plug 'm2mdas/phpcomplete-extended', { 'for': [ 'php'] }
"Plug 'maksimr/vim-translator', { 'for': [ 'md', 'txt'] }
"Plug 'mattn/emmet-vim'
"Plug 'plasticboy/vim-markdown'
"Plug 'scrooloose/syntastic'
"Plug 'tpope/vim-obsession'
"Plug 'vim-scripts/textutil.vim'
"Plug 'mhinz/vim-startify'
Plug 'wakatime/vim-wakatime'
" Plug 'ervandew/supertab'
" Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets', { 'for': [ 'php'] }
Plug 'adoy/vim-php-refactoring-toolbox', { 'for': [ 'php'] }
Plug 'ajh17/VimCompletesMe'
Plug 'altercation/vim-colors-solarized'
" Plug 'bkad/CamelCaseMotion'
" Plug 'bling/vim-airline'
Plug 'christoomey/vim-tmux-navigator'
"Vim plugin for pretty printing the arg list.
" Plug 'coot/vim_args'
"rename tabs
" Plug 'gcmt/taboo.vim'
Plug 'jiangmiao/auto-pairs'
"Plug 'Townk/vim-autoclose'
" Plug 'kien/ctrlp.vim'
" Plug 'airblade/vim-gitgutter'
Plug 'lervag/vimtex', { 'for': ['latex'] }
" Plug 'luochen1990/rainbow', { 'for': [ 'php'] }
" display tags on it's own v'iew
" Plug 'majutsushi/tagbar'
"  <count>ai         (A)n (I)ndentation level and line above.
"  <count>ii         (I)nner (I)ndentation level (no line above).
"  <count>aI         (A)n (I)ndentation level and lines
"  above/below.
"  <count>iI         (I)nner (I)ndentation level (no lines above/below). 
" Plug 'michaeljsmith/vim-indent-object'
Plug 'mileszs/ack.vim'
Plug 'nelstrom/vim-visual-star-search'
Plug 'pangloss/vim-javascript', { 'for': [ 'javascript'] }
" Plug 'rayburgemeestre/phpfolding.vim', { 'for': [ 'php' ] }
"Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
"add end in ruby
" Plug 'tpope/vim-endwise'
"git tools
" Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
"readline behaviour
Plug 'tpope/vim-rsi'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-scripts/Mark--Karkat'
Plug 'vim-scripts/argtextobj.vim'
" Plug 'mattn/vim-metarw-gdrive'
" Plug 'vim-scripts/closetag.vim', { 'for': [ 'html'] }
Plug 'mattn/webapi-vim' | Plug 'mattn/gist-vim'
" Plug 'joonty/vdebug'
" Plug 'wincent/Command-T'
" Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
"Plug 'andreimaxim/vim-io', { 'for': [ 'io'] }
"Plug 'chrisbra/BufTimer'
"Plug 'gisraptor/vim-lilypond-integrator'
"Plug 'vim-scripts/marvim'


call plug#end()

" let g:rainbow_conf = {
" \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
" \   'ctermfgs': ['Blue', 'Magenta', 'DarkGreen', 'DarkYellow'],
" \}

"Marks 
" Highlight words to avoid in tech writing
" http://css-tricks.com/words-avoid-educational-writing/
runtime plugin/mark.vim
silent MarkClear


" let g:rustfmt_autosave = 1 

"bad words
Mark /\cobviously\|basically\|simply\|of\ scourse\|clearly\|just\|everyone\sknows\|however\|so,\|easy/
Mark /\obviamente\|basicamente\|simplesmente\|com\ certeza\|claramente\|apenas\|mais\|todos\sabem\|entretanto\|então,\|fácil\|bem/

"mark duplicated words and excedent whitespaces
" highlight WrongPatterns ctermbg=red guibg=red
" autocmd InsertEnter * match WrongPatterns /\w\s\{2,\}\w\|\s\+$\|\v<(\w+)\_s+\1>/
" autocmd InsertLeave * match WrongPatterns /\w\s\{2,\}\w\|\s\+$\|\v<(\w+)\_s+\1>/
" autocmd BufWinEnter * match WrongPatterns /\w\s\{2,\}\w\|\s\+$\|\v<(\w+)\_s+\1>/
" match WrongPatterns /\w\s\{2,\}\w\|\s\+$\|\v<(\w+)\_s+\1>/
" autocmd BufWinLeave * call clearmatches()
"end mark text errors"

" let marvim_store = '/home/jean/projects/vimrc/vim/marvim' 
" let marvim_find_key = '<leader>mf' " change find key from <F2> to 'space' 
" let marvim_store_key = '<leader>ms'     " change store key from <F3> to 'ms' 
"let marvim_register = 'c'       " change used register from 'q' to 'c' 
"let marvim_prefix = 0           " disable default syntax based prefix 

nnoremap <C-p> :Unite file_rec/async<cr>
nnoremap <leader>/ :Unite grep:.<cr>
nnoremap <leader>b :Unite -quick-match buffer<cr>
call unite#custom#profile('context.ignorecase', 'context.ignorecase', 1)
call unite#custom#source('file_rec/async', 'ignore_pattern', 'vendor/')

"snippets
augroup load_us
  autocmd!
  autocmd InsertEnter * call plug#load('ultisnips')
augroup END

" let g:SuperTabDefaultCompletionType = '<C-n>'
" let g:SuperTabDefaultCompletionType.= "<c-x><c-o>"
" let g:UltiSnipsExpandTrigger="<tab>"
" let g:UltiSnipsJumpForwardTrigger="<c-b>"
" let g:UltiSnipsJumpBackwardTrigger="<c-z>"

let g:netrw_localrmdir='rm -r'
"put line numbers on netrw
let g:netrw_bufsettings = 'noma nomod nu nobl nowrap ro'
let g:netrw_liststyle=3
let g:netrw_list_hide= '^\.'
" let g:rainbow_active = 1 "0 if you want to enable it later via :RainbowToggle
let &runtimepath.=',/home/jean/.vim/plugin/ns9tks-vim-l9-3bb534a720fa'
let &runtimepath.=',/home/jean/.vim/plugin/ns9tks-vim-autocomplpop-13fe3d806464'
" let g:ctrlp_max_files=0
" let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
" if executable('ag')
"       let g:ctrlp_user_command = 'ag %s -U -l --nocolor -g ""'
" endif
"let NERDTreeMouseMode=3
" let NERDTreeDirArrows=0
"let NERDTreeMinimalUI=1
" let NERDTreeShowLineNumbers=1


"autocmd FileType php setlocal omnifunc=phpcomplete_extended#CompletePHP

"colorscheme 
colorscheme solarized
"set t_Co=16
"let g:solarized_termcolors=16

"makes a underline on the current cursor line
:hi CursorLine cterm=underline ctermbg=NONE
:hi clear SpellBad
:hi SpellBad cterm=bold ctermbg=red

nnoremap <BS> :Rex<cr>
nnoremap <Leader>q :q<cr>
nnoremap <Leader>p :set paste!<cr>
nnoremap <Leader>e :edit!<cr>
nnoremap <Leader>o :only<cr>
nnoremap cwi ciw
" inoremap <C-z> <Esc>[s1z=gi
map - ddp
map _ dd2kp
map <leader>spt :set spell spelllang=pt_br<cr>
map <leader>sen :set spell spelllang=en_us<cr>
map <leader>i mmgg=G`m
map <leader>x :w<','> !bash<cr>
" map <leader>bt :call ToggleBackgroundColour()<cr>
map <leader>me :!chmod +x %<cr>
map <leader>gp :!chmod 777 %<cr>
map <leader>mk :!make<cr>
map <leader>ck :!git checkout %<cr>
nmap <leader>of :!xdg-open % &<cr>
"open director (file manager)
nmap <leader>od :!thunar %:h<cr>
nmap <leader>rmrf :!rm -rf %:p <cr>
" nmap <leader>k :NERDTreeToggle<cr>
nmap <leader>k :Explore<cr>
nmap <leader>pn :!echo %<cr>
nmap <leader>pfn :!echo %:p<cr>
nmap <leader>cfn :!copy %:p<cr>
nmap <leader>c <C-w>v<C-w>l<cr> :VimShell<cr>
nmap <leader>t :TagbarToggle<cr>
nmap <leader>bsc :BlogSaveContent<cr>
nmap <leader>bsm :BlogSaveMeta<cr>
nmap <leader>gk :!gitk %<cr>
nmap <leader>dw \(\<\w\+\>\)\_s*\<\1\><cr>
nmap <silent> <leader>ev :e $MYVIMRC<cr>
nmap <silent> <leader>sv :so $MYVIMRC<cr>
" nmap <silent> <leader>sn :e /home/jean/projects/snippet/vim/UltiSnips/php.snippets<cr>
" nmap <silent> <leader>snc :e /home/jean/projects/snippet/vim/UltiSnips/php_clipp.snippets<cr>
nnoremap <leader>c :noh<cr>
" nnoremap <leader>cc :CtrlPClearAllCaches<cr>
nnoremap <leader><space> :w<cr>
cmap w!! w !sudo tee % >/dev/null
"use C-p and C-n to browser normal mode commands history
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
" use %% to expand to the current buffer directory
cnoremap <expr> %% getcmdtype() == ':' ? expand('%:h').'/' : '%%'

let g:vimwiki_list = [{'path': '~/projects/writing/', 'syntax': 'markdown', 'ext': '.md'},
            \ {'path': '~/projects/compufacil/Docs/', 'syntax': 'markdown', 'ext': '.md'}]

"Commands 
"php
command Phpcsfixer : ! php-code-check `pwd`/%
    \ || print "Error on code check" && sleep 10

function! RunPHPUnitTest(filter)
    cd %:p:h
    if a:filter
        normal! T yw
        let myCommand="cgexec -g memory:development phpunit -c ". $PWD ."/phpunit.xml.dist --filter " . @" . " " . expand("%:p")
        let result = system(myCommand)
    else
        let myCommand = "cgexec -g memory:development phpunit -c ". $PWD . "/phpunit.xml.dist " . expand("%:p")
        let result = system(myCommand)
    endif
    split __PHPUnit_Result__
    normal! ggdG
    setlocal buftype=nofile
    call append(0, myCommand)
    call append(0, split(result, '\v\n'))
    cd -
endfunction

"command Phpmystandard : ! printf "PHP my standard \n" && make-php `pwd`/%
autocmd filetype php nnoremap <leader>s :Phpcsfixer<cr>
"autocmd filetype php nnoremap <leader>m :Phpmystandard<cr>
nnoremap <leader>u :call RunPHPUnitTest(0)<cr>
nnoremap <leader>f :call RunPHPUnitTest(1)<cr>

command BlogSaveContent : ! printf "Saving post online \n %:t:r % " && blog-update %:t:r %
command BlogSaveMeta : ! printf "Saving post meta online \n %:t:r % " && blog-meta-update %:t:r %
com! FormatJSON %!python -m json.tool
au BufNewFile *.html 0r /home/jean/projects/snippet/template/html.html
au BufNewFile *.php 0r /home/jean/projects/snippet/template/php.php

function! OnlineDoc()
  if &ft =~ "cpp"
    let s:urlTemplate = "http://doc.trolltech.com/4.1/%.html"
  elseif &ft =~ "ruby"
    let s:urlTemplate = "https://www.google.com.br/?q=ruby+%"
  elseif &ft =~ "php"
    let s:urlTemplate = "http://php.net/manual-lookup.php?pattern=%&scope=quickref"
  elseif &ft =~ "perl"
    let s:urlTemplate = "http://perldoc.perl.org/functions/%.html"
  else
    return
  endif
  let s:browser = "browser"
  let s:wordUnderCursor = expand("<cword>")
  let s:url = substitute(s:urlTemplate, "%", s:wordUnderCursor, "g")
  let s:cmd = "silent !" . s:browser . " " . s:url . "&"
  execute s:cmd
  redraw!
endfunction
" Online doc search.
map <Leader>doc :call OnlineDoc()<cr>
map <silent> <M-d> :call OnlineDoc()<cr>

" Merge a tab into a split in the previous window
function! MergeTabs()
  if tabpagenr() == 1
    return
  endif
  let bufferName = bufname("%")
  if tabpagenr("$") == tabpagenr()
    close!
  else
    close!
    tabprev
  endif
  split
  execute "buffer " . bufferName
endfunction
nmap <C-W>u :call MergeTabs()<CR>


function! RenameFile()
  let old_name = expand('%')
  let new_name = input('New file name: ', expand('%'), 'file')
  if new_name != '' && new_name != old_name
    exec ':saveas ' . new_name
    exec ':silent !rm ' . old_name
    redraw!
  endif
endfunction
map <Leader>r :call RenameFile()<cr>


function! DoPrettyXML()
  " save the filetype so we can restore it later
  let l:origft = &ft
  set ft=
  " delete the xml header if it exists. This will
  " permit us to surround the document with fake tags
  " without creating invalid xml.
  1s/<?xml .*?>//e
  " insert fake tags around the entire document.
  " This will permit us to pretty-format excerpts of
  " XML that may contain multiple top-level elements.
  0put ='<PrettyXML>'
  $put ='</PrettyXML>'
  silent %!xmllint --format -
  " xmllint will insert an <?xml?> header. it's easy enough to delete
  " if you don't want it.
  " delete the fake tags
  2d
  $d
  " restore the 'normal' indentation, which is one extra level
  " too deep due to the extra tags we wrapped around the document.
  silent %<
  " back to home
  1
  " restore the filetype
  exe "set ft=" . l:origft
endfunction
command! PrettyXML call DoPrettyXML()

